### ISSUE TITLE
Windows Update Last Installed

### ISSUE THREAD

**Issue by solarplex** [pdq/PowerShell-Scanners#13]
I'm looking into getting this one pushed out and i was getting a "not recognized" cmdlet from it.

When looking up Get-WULastInstallationDate it shows the source as WindowsUpdateProvider not PSWindowsUpdate. 

Can anyone else confirm this? 

PSWindowsUpdate on PowerShell Gallery doesn't show Get-WULastInstallationDate as one of the cmdlets.

Looking at what PSWindowsUpdate has to offer:
```
& '.\Install and Import Module.ps1' -ModuleName "PSWindowsUpdate"

$Results = Get-WULastResults
$RebootStatus = Get-WURebootStatus -Silent

[PSCustomObject]@{
    LastInstallationDate = [DateTime]($results.LastInstallationSuccessDate)
    LastScanSuccessDate  = [DateTime]($results.LastSearchSuccessDate)
    IsPendingReboot      = [Bool]($RebootStatus.RebootRequired)
}
```

**Comment by Colby-PDQ** [comment]
Huh, fascinating! When I wrote this one I assumed that WindowsUpdateProvider was somehow related to PSWindowsUpdate. Thanks for the suggested fix!
