### ISSUE TITLE
Google Chrome Scan Issue

### ISSUE THREAD

**Issue by Phillyphotog** [pdq/PowerShell-Scanners#23]
Was able to get some scan results off of a system, but an error returned:

VERBOSE: Found --- C:\Users\aw***\AppData\Local\Google\Chrome\User Data\Default\Preferences
ERROR: Cannot convert the JSON string because a dictionary that was converted from the string contains the duplicated keys 'www.cdwg.com/accountcenter/LogOn' and 'www.cdwg.com/accountcenter/logon'.
At line:37 char:55
+     $PreferencesJson = Get-Content $PreferencesFile | ConvertFrom-Json

VERBOSE: Found --- C:\Users\ef***\AppData\Local\Google\Chrome\User Data\Default\Preferences

**Comment by Phillyphotog** [comment]
Scanner returned error 

Cannot convert the JSON string because a dictionary that was converted from the string contains the duplicated keys 'www.cdwg.com/accountcenter/LogOn' and 'www.cdwg.com/accountcenter/logon'.

**Comment by PDQDakota** [comment]
We'll take a look at this and see what can be done.

**Comment by Colby-PDQ** [comment]
@Phillyphotog I pushed a potential fix for this issue. Please update your copy of the repo and let me know if it helped.

**Comment by Phillyphotog** [comment]
Unable to replicate result on previous system that was exhibiting the issue while running version of scanner loaded in on 7/8/2020.  Assuming that there was a conflict with version of Chrome that was being run (was current/one minor release behind) as of time of report.  Will go ahead and update to new release of scanner and test as well.

**Comment by Phillyphotog** [comment]
New pull looks pretty clean as well.  Clean scans on about 300+ systems.

I did get errors on 5 2012 R2 systems, however, this is a new error.  I did not have any successful scans on 2012 systems, but did have scans successful on 2016 and 2019. No issues on W7 or W10

Method invocation failed because [System.Web.Script.Serialization.JavaScriptSerializer] does not contain a method named 'New'.

VERBOSE: Found --- C:\Users\a*******\AppData\Local\Google\Chrome\User Data\Default\Preferences
ERROR: Method invocation failed because [System.Web.Script.Serialization.JavaScriptSerializer] does not contain a method named 'New'.
At line:41 char:5
+     $JsonParser = [System.Web.Script.Serialization.JavaScriptSerializer]::New()

ERROR: You cannot call a method on a null-valued expression.
At line:42 char:5
+     $PreferencesJson = $JsonParser.DeserializeObject($PreferencesText)

ERROR: You cannot call a method on a null-valued expression.
At line:44 char:29
+     Foreach ( $Extension in $PreferencesJson.extensions.settings.GetEnumerator() ) {

VERBOSE: Found --- C:\Users\b********\AppData\Local\Google\Chrome\User Data\Default\Preferences
ERROR: Method invocation failed because [System.Web.Script.Serialization.JavaScriptSerializer] does not contain a method named 'New'.
At line:41 char:5
+     $JsonParser = [System.Web.Script.Serialization.JavaScriptSerializer]::New()

ERROR: You cannot call a method on a null-valued expression.
At line:42 char:5
+     $PreferencesJson = $JsonParser.DeserializeObject($PreferencesText)

ERROR: You cannot call a method on a null-valued expression.
At line:44 char:29
+     Foreach ( $Extension in $PreferencesJson.extensions.settings.GetEnumerator() ) {

VERBOSE: Found --- C:\Users\j*****\AppData\Local\Google\Chrome\User Data\Default\Preferences
ERROR: Method invocation failed because [System.Web.Script.Serialization.JavaScriptSerializer] does not contain a method named 'New'.
At line:41 char:5
+     $JsonParser = [System.Web.Script.Serialization.JavaScriptSerializer]::New()

ERROR: You cannot call a method on a null-valued expression.
At line:42 char:5
+     $PreferencesJson = $JsonParser.DeserializeObject($PreferencesText)

ERROR: You cannot call a method on a null-valued expression.
At line:44 char:29
+     Foreach ( $Extension in $PreferencesJson.extensions.settings.GetEnumerator() ) {

VERBOSE: Found --- C:\Users\kw*****\AppData\Local\Google\Chrome\User Data\Default\Preferences
ERROR: Method invocation failed because [System.Web.Script.Serialization.JavaScriptSerializer] does not contain a method named 'New'.
At line:41 char:5
+     $JsonParser = [System.Web.Script.Serialization.JavaScriptSerializer]::New()

ERROR: You cannot call a method on a null-valued expression.
At line:42 char:5
+     $PreferencesJson = $JsonParser.DeserializeObject($PreferencesText)

ERROR: You cannot call a method on a null-valued expression.
At line:44 char:29
+     Foreach ( $Extension in $PreferencesJson.extensions.settings.GetEnumerator() ) {

VERBOSE: Found --- C:\Users\S****\AppData\Local\Google\Chrome\User Data\Default\Preferences
ERROR: Method invocation failed because [System.Web.Script.Serialization.JavaScriptSerializer] does not contain a method named 'New'.
At line:41 char:5
+     $JsonParser = [System.Web.Script.Serialization.JavaScriptSerializer]::New()

ERROR: You cannot call a method on a null-valued expression.
At line:42 char:5
+     $PreferencesJson = $JsonParser.DeserializeObject($PreferencesText)

ERROR: You cannot call a method on a null-valued expression.
At line:44 char:29
+     Foreach ( $Extension in $PreferencesJson.extensions.settings.GetEnumerator() ) {

**Comment by Colby-PDQ** [comment]
I'm closing this issue because the original problem has been fixed. I will create a new issue for the 2012 R2 problem.
