### ISSUE TITLE
Google Chrome Extensions scanner fails on some 2012 R2 machines

### ISSUE THREAD

**Issue by Colby-PDQ** [pdq/PowerShell-Scanners#25]
This one's weird because the scanner works fine on most of the 2012 R2 machines we have in the PDQ.com lab. Only a few of them throw `Method invocation failed because [System.Web.Script.Serialization.JavaScriptSerializer] does not contain a method named 'New'`. I haven't been able to find the difference between the broken and working machines yet.

This has been seen in the wild too: https://github.com/pdq/PowerShell-Scanners/issues/23#issuecomment-665244014

**Comment by PDQDakota** [comment]
Fixed in PR #33
