### ISSUE TITLE
Script may be missing Error Out

### ISSUE THREAD

**Issue by Phillyphotog** [pdq/PowerShell-Scanners#3]
I believe the Shared Script is missing " -ErrorAction Stop" in the Try portion.

It should read 
Try {

    $null = Get-InstalledModule $ModuleName -ErrorAction Stop

} Catch {

This will kill the action, triggering the catch statement.  Without it, the script skips the catch step and moves on to attempting to import a missing module.

**Comment by Colby-PDQ** [comment]
You're absolutely right. Thanks for catching this!

**Comment by Colby-PDQ** [comment]
Fixed by #4.
