### ISSUE TITLE
Get Bitlocker Information

### ISSUE THREAD

**Issue by MFKDGAF** [pdq/PowerShell-Scanners#30]
This scanner name (Get Bitlocker Information) does not match the name of the scan profile (Bitlocker Information).
When doing a git pull and comparing what was added, it makes it easier to compare when the scanner and scan profile names are the same.

Possibly update https://github.com/pdq/PowerShell-Scanners/blob/master/Policies/Contributing.md to reflect this?

**Comment by PDQDakota** [comment]
This was solved in #34 thanks for submitting this issue!
