### ISSUE TITLE
RDP Last Logoff

### ISSUE THREAD

**Issue by MFKDGAF** [pdq/PowerShell-Scanners#41]
This scanner name (RDP Last Logoff) does not match the name of the scan profile (Last Log off).
When doing a git pull and comparing what was added, it makes it easier to compare when the scanner and scan profile names are the same.

This was done in the past with https://github.com/pdq/PowerShell-Scanners/issues/30

**Comment by PDQDakota** [comment]
This was fixed in #45 
Thank you for reporting the issue!
