### ISSUE TITLE
User Ad Groups - returns "Cannot index into a null array"

### ISSUE THREAD

**Issue by AndrewPla** [pdq/PowerShell-Scanners#73]
I receive an error "cannot index into null array" for some machines. These machines have an `$account.LastLoggedOnUserSID` of `S-1-5-21-####-####-####-500`

I get the error `Cannot index into a null array.` on line 13, which is `$groups = $ds.FindOne().Properties['memberof']`

I think that we need to only access the 'MemberOf' property only if $ds.findone() has results.

https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/security-identifiers-in-windows

**Comment by CaseyM-PDQ** [comment]
Fixed with latest merge
