### ISSUE TITLE
May be broken in 20H2

### ISSUE THREAD

**Issue by Phillyphotog** [pdq/PowerShell-Scanners#74]
Not able to pull results on 20H2 systems it appears.  No error being returned from scan attempt, scan result fails to store within PDQ

**Comment by PDQDakota** [comment]
Would you post steps for us to recreate this issue?

**Comment by Phillyphotog** [comment]
Updated my local copy of Git repository
Created Powershell Scanner, pointing to powershell scanner script in question (Windows Update History)
Ran Scanner manually through right click menu

**Comment by ColbyBouma** [comment]
I believe this is the same issue as: https://help.pdq.com/hc/en-us/community/posts/4405514434331-PS-Windows-Update-History-question

Potential fix incoming.
