### ISSUE TITLE
Get Windows Updates error

### ISSUE THREAD

**Issue by JohPAM** [pdq/PowerShell-Scanners#75]
When a client (Windows 10  and Server 2016) has no available updates, the scanner ends with the error: Cannot bind argument to parameter 'Command' because it is null.
At line:38 char:72

This can be solved by checking if $_.Size is empty or not, directly after the ForEach-Object step. If it's empty, it will be set to $null. If it has a value, it wil we converted to Uint64.

`$GWU | ForEach-Object {

	If ($_.Size) {
		# Convert to bytes so it will display properly in Inventory
		$Size = [UInt64](Invoke-Expression $_.Size)
	}
	Else {
		$Size = $null
	}`

**Comment by ColbyBouma** [comment]
I believe that was fixed a while ago: https://github.com/pdq/PowerShell-Scanners/commit/1bbdadab2a4c6266a7109750ac8f2f4d6e1e246f
I recommend making sure your copy of this repository is up to date.

**Comment by JohPAM** [comment]
Hi Colby,

I'm on the latest version of the script. I pull the Git repo on a weekly basis using a PDQ package (of course 😄). I had contact with your colleague Andrew in ticket 270628 and he advised me to create an issue. He couldn't reproduce the issue, but I have the issue on Windows 10 and Server 2016. It can easily be test when executing the command `[UInt64](Invoke-Expression $_.Size)` in a new PowerShell session. This throws an error, because you can't execute Invoke-Expression with an empty variable.

Regards,
Johan Pronk

**Comment by AndrewPla** [comment]
Hi Johan,

Thanks for opening up an issue for this. It sounds like rather than an empty object being returned it was just not returning a size for the object which was causing issues.

**Comment by JohPAM** [comment]
Hi Andrew,

That is correct. And it's not returning a size, because you can't run `Invoke-Expression` with an empty value. Than the whole script stops running.

**Comment by CaseyM-PDQ** [comment]
Issue was closed with #77
