### ISSUE TITLE
Hosts File scanner does not update results when scanning empty hosts file

### ISSUE THREAD

**Issue by GibbyPDQ** [pdq/PowerShell-Scanners#83]
It has been reported that the Hosts File scanner does not update data in Inventory if the Hosts file is blank.  Testing will need to be done to verify, if confirmed scanner will need to be modified to account for empty Hosts files.

https://github.com/pdq/PowerShell-Scanners/tree/master/PowerShell%20Scanners/Hosts%20File

**Comment by ColbyBouma** [comment]
Dear PDQ, **please** fix Inventory itself. That bug has existed for well over a year. "Fixing" each PowerShell script is a poor solution.

* https://github.com/pdq/PowerShell-Scanners/issues/79
* https://help.pdq.com/hc/en-us/community/posts/4409356834075-PowerShell-Scanner-Leaving-Behind-Old-Data
* https://help.pdq.com/hc/en-us/community/posts/4408418974107-Powershell-Scan-for-PDQi-Device-Manager-Errors
* https://old.reddit.com/r/pdq/comments/mmwhje/stale_ps_scanner_data/
* https://old.reddit.com/r/pdq/comments/m80ei1/powershell_scanner_issue/

**Comment by AndrewPla** [comment]
@ColbyBouma I appreciate your feedback and have shared it internally. We are hoping that this gets fixed soon and is high up on the list, but unfortunately don't have a timeline to share with you at this time.

**Comment by Anumann** [comment]
Hi,

Does that mean the scanner will gracefully handle an empty hosts file? Are
you able to provide any more detail before closing this please?



--

Alexander Numann

Lead Mechanical Engineer

He / Him / His



<https://productdevelopment.nextfab.com/?utm_source=staff&utm_medium=email&utm_campaign=signature>

*productdevelopment.nextfab.com
<https://productdevelopment.nextfab.com/?utm_source=staff&utm_medium=email&utm_campaign=signature>*

2025 Washington Ave. Philadelphia, PA

**Comment by AndrewPla** [comment]
Hi @Anumann, apologies for the lack of clarity on my part. We merged a change in #88 to fix this.

**Comment by Anumann** [comment]
Hi Andrew,

Got it, understood. Thanks for the quick response!

--

Alexander Numann

Lead Mechanical Engineer

He / Him / His



<https://productdevelopment.nextfab.com/?utm_source=staff&utm_medium=email&utm_campaign=signature>

*productdevelopment.nextfab.com
<https://productdevelopment.nextfab.com/?utm_source=staff&utm_medium=email&utm_campaign=signature>*

2025 Washington Ave. Philadelphia, PA
