### ISSUE TITLE
TLS1.1Server path variable

### ISSUE THREAD

**Issue by Urfried** [pdq/PowerShell-Scanners#89]
There is a typo in TLSv1.1 Path variable (line 121 + 125), in Cipher suite detection script. 
The path is set with $TLSv1_1ServerEnabled. 
Change it to $TLSv1_1Server and it works. 

Actually. Referring to Cipher suite detection is wrong. 
This script detects Transport Layer protocol. 

Collecting cipher suites can be done with a very simple one liner;
(Get-TlsCipherSuite).Name

**Comment by crimsy** [comment]
I found this and corrected it on my local install.  It works. I am surprised this has not been committed yet.

**Comment by AndrewPla** [comment]
We have merged #93 which addresses this.
