### ISSUE TITLE
LLMNR Enabled

### ISSUE THREAD

**Issue by mrtowering** [pdq/PowerShell-Scanners#91]
Get-ItemProperty needs changed to Get-ItemPropertyValue in some lines to fix error in running the script.

**Comment by CaseyM-PDQ** [comment]
Thanks for bringing this up! When I test this in my environment I do not get any errors. 
However, I also do not have any devices where LLMNR is enabled, so it may be something there.
What errors are you getting on your side? Is it specific machines (O/S, LLMNR value, etc...) that throw this error, or all?

Changing Get-ItemProperty to Get-ItemPropertyValue threw "Get-ItemPropertyValue: Property EnableMulticast does not exist" errors for me. Which instances of Get-ItemProperty work better for you as Get-ItemPropertyValue?

Let us know and we can dig a bit deeper into this.

**Comment by AndrewPla** [comment]
Going to get this one closed out, but if you have a chance to look into what @CaseyM-PDQ let us know and we can take a closer look
