### ISSUE TITLE
Property Enabled does not exist

### ISSUE THREAD

**Issue by ClaytonMurphy** [pdq/PowerShell-Scanners#92]
Observed on Server 2016. The registry value "Enabled" does not exist under HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Client, causing the script to return an error. Instead, the value under this key is "DisabledByDefault"

![image](https://user-images.githubusercontent.com/105801694/169071973-1a3fe81d-44cf-470e-94d0-75ff6c2fb334.png)

**Comment by matthttam** [comment]
I've rewritten this script and will do a pull request once I have time to test it the rest of the way.

**Comment by AndrewPla** [comment]
This is addressed in #93
