### ISSUE TITLE
Get Available Windows Updates not updating when nothing found

### ISSUE THREAD

**Issue by JohPAM** [pdq/PowerShell-Scanners#94]
When there are no mapped drives found, PDQ Inventory isn't updated and the values of the previous scan will remain visible.

**Comment by AndrewPla** [comment]
I recommend getting on the release that was released yesterday. It includes a bug fix for what you are experiencing. "Inventory: PowerShell Scanner clears results when return is null."  
https://www.pdq.com/releases/

**Comment by JohPAM** [comment]
> I recommend getting on the release that was released yesterday. It includes a bug fix for what you are experiencing. "Inventory: PowerShell Scanner clears results when return is null." https://www.pdq.com/releases/

Hi Andrew, updating the software fixed the problem. Thanks for the quick response!

Regards,
Johan Pronk
