### ISSUE TITLE
Search Using Primary User only

### ISSUE THREAD

**Issue by cengbrecht** [pdq/PowerShell-Scanners#98]
In testing I have found that this works amazingly well, thought I must confess, I would like to see a filter to only search plugins for a %username% if run as the logged in user. (Not the whole history of users I mean)
If this is already a thing, I apologize.

**Comment by ColbyBouma** [comment]
@cengbrecht Does #99 do what you want?

**Comment by cengbrecht** [comment]
Indeed its seems that it would.

Would you be so kind as to show me where all the tac options are? I read the Readme , but couldn't find them all?

**Comment by ColbyBouma** [comment]
They're under the Parameters section. To use the parameter I just added, you would put `-OnlyCurrentUser` in the Parameters field of the scanner. However, my changes are currently pending, so to test this you will either have to wait for it to be approved, or download my branch.

```
cd C:\PowerShell-Scanners\
git fetch origin pull/99/head:Extensions-Current-User
git checkout Extensions-Current-User
```

When you're done testing:

```
git checkout master
```
